apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jira-azure
  namespace: jira-prod
spec:
  interval: 10m
  chart:
    spec:
      chart: ./k8s/helm/jira
      sourceRef:
        kind: GitRepository
        name: jira-repo
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 3
    image:
      repository: atlassian/jira-software
      tag: "9.0.0"
    resources:
      requests:
        cpu: "2"
        memory: "8Gi"
      limits:
        cpu: "4"
        memory: "16Gi"
    jira:
      jvmMaxHeap: "12g"
      db:
        host: "jira-prod-postgres.postgres.database.azure.com"
        passwordSecretName: "jira-db-secret"
      sharedHome:
        azureFiles:
          storageAccountName: "jiraprodstorageacct"
          shareName: "jira-shared-home"
    ingress:
      enabled: true
      className: azure-application-gateway
      hosts:
        - host: jira.company.com
          paths:
            - path: /
              pathType: Prefix
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3