apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jira
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<org>/jira-on-aws-eks.git
    targetRevision: main
    path: k8s/helm/jira
    helm:
      valueFiles:
        - values.yaml
        - values-azure.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: jira-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
